sudo: required

services:
  - docker

env:
  global:
    - secure: "mGfYZZ68MPHQrrheEBm18QNTGMNCGBaunnG7vgb8z0cbCbdhVPvqyNNKAkVu76XVblXxqmqqBSXkdKJ5LsN2EhY8qhmE7uxCvlOn3wimVUpwjqv7/2DJAskWvN2tHWfDogYmEwZg+KlsVDCpqK4Iy7DpFDWVnQGxtXnVuutC3ElpTSCwidEh2y6govZt4Kt5CGRmwS8SFhCu6udvWOlpzRiXlnRGf6HHwqAw3YAPGWguwOyAbPTfO4eEN7iD3T22a0hjvf+Txr1M07UlBKhPtovFVVWbOA3knlPX/OuNpv92MhcNPUvHIqkN3aNC9rxPUlRnt9eB/Kvvk105j9nH55F4Ooh20P8IQrbD5ZXPt4Uu7k8tfO6+V2hthbwf4eXgA6Q3k1vhX0dAVoSo6dsuYk2MZU8j42tXFWomP8ZKyA5IBtujuGjJaTIHLcwPICWrYLhHobmHV3MfGZHr5Kpg/lGJCMh9ZxeyuAMA22FFxzdpnFLjR3ZVjpde5lPxnusB30Qr7mGXts058cMeDevcQWFiJ6bzpr2ppD1la+z3rDWbA3nrPXyHljJiZ7xVH+LfeyIPPUoiyVEOv1AL1MGQ4SoQJilXY9TBBQljEgSM311jZI+elOYN6u3+MRqaodKK5e7WuFR1z9Kd8UT/rmI9uODvEDGxwKrjR9Yw9d4lsE0="
    - secure: "Nblx52rEQTcJ6Sv6W5350cNw6zny0yRMIzLZZWBKZyG9MgFjnKPv70Dl103KXVXZafDy9sA6R6sU9aLUA3///IZ+gO/jf92KY9TOvOCCez/f1IeUJ1rcaZZHS87js0AAEb/Mj35FSZBpCsiqMBP2DnF9XeShmAwOVJ/2Lb3UqUrADPSmNHQnObTI4n0qxMmP7HwjbUCEFS8Wpes70pk2wwcg6QrFLmfLmZK8hpYc887LcYP2io6MGJ9JpcKHyEUd+fpFnnKGlXWERhjQLuq45greG9V24c+ZBppt/UpljnEFzYQEqJptwYeB2sS4kJrN7Zhx5vcSGXTCPZn09ClRI8HZJpjnfsijJowPZygfd0nu1GSyEjz5ETpko0AhS+cIvevX6aCsVFd7VK8GeFhCOQYqATB6Apu2Pmz8NZ1jEHPjbhbuj7gD97gEVj0AK7NtCXuVF+OzDkCDy3ZlpgnSxHS0ZJXFJZeb/QlDrqHH4uMuSSdG0GvB7KETQKQ7PUzqAqyKXAMZPQEiPsvTcWdXuUzaS6EQVarVel9CCrGrwHswngs+SSDdbnyRP9OxXaoCW5J0j5e4Rmd4Ertl8iD2/c0ztzDE2H/oaFJ7KMAGi97KlCaPO4KrGNHnXKnPdhPz+40QgM8HH4kqBNdYniWEmIXDOtWEQR+JyVBmx5OBnqE="

script:
  - bash docker-build.sh

# Do some informational output
before_deploy:
  - docker images

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master

# Do some informational output
after_script:
  - docker images

